### ISSUE TITLE
npm install: No compatible version found: redsmin@'latest'

### ISSUE THREAD

**Issue by mitchellporter** [Redsmin/proxy#29]
I am using `npm version 2.15.9` and `node version 4.5.0`

I keep trying the following command in terminal on mac: `npm install -g redsmin`

Anytime I try this I get the following error:
`notarget No compatible version found: redsmin@'latest'`

I have tried variations with `--global` and also the copy/paste that redsmin.com gives you that includes the `REDSMIN_KEY`.

None of these work and always result in the same output.

**Comment by mitchellporter** [comment]
To fix this I set my version to 3.0.0 as it looks like this may have been caused by using `node version 4.5.0` instead of `node version 6.0.0.`

**Comment by FGRibreau** [comment]
Because latest redsmin proxy is compatible with NodeJS v6+.
