### ISSUE TITLE
Connecting from container to localhost doesn't work

### ISSUE THREAD

**Issue by Rambatino** [Redsmin/proxy#32]
I followed the documentation in your README, however it didn't work even when substituting the correct ip address in. 

However, a much easier way to achieve all of this on a mac is using `docker.for.mac.localhost`:

``` bash
docker run -it --rm --name redsmin-proxy -eREDSMIN_KEY=KEY -e REDIS_URI="redis://docker.for.mac.localhost:6379" redsmin/proxy```

Thought I'd raise it here as I think it's a better solution than the one you have.

**Comment by FGRibreau** [comment]
Fixing it in readme, thanks!
