### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by matthewblott** [Redsmin/proxy#34]
I've installed but it crashes every time I run the ```redsmin``` command. The problem seems to be the ```env.js``` file. I did inspect it and the JavaScript looks invalid to me, this is the line that throws the error ....

```
const {
  CommonEnvInvalidConfiguration,
  CommonEnvRootConfigurationObjectException,
  CommonEnvGetOrDieAliasesException,
  CommonEnvGetOrDieException
} = errors;
```

However, I changed this and it just crashes on another line further down that looks okay. I've tried uninstalling and reinstalling etc but have had no joy. Thanks :-)

**Comment by FGRibreau** [comment]
Did you update NodeJS to latest version?
